# Generated by Django 4.2.7 on 2026-04-01 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cloudinary_url', models.URLField(max_length=500)),
                ('public_id', models.CharField(max_length=200)),
                ('file_name', models.CharField(max_length=200)),
                ('file_size', models.IntegerField()),
                ('row_count', models.IntegerField(default=0)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('dates_par_jour', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Planning stocké',
                'verbose_name_plural': 'Plannings stockés',
                'ordering': ['-upload_date'],
            },
        ),
    ]
