# Generated by Django 4.2.7 on 2026-04-02 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_planningstorage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlanningStorage',
        ),
    ]
