# Generated by Django 4.2.7 on 2026-04-17 00:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion', '0003_delete_planningstorage'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationadmin',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_admin', to=settings.AUTH_USER_MODEL, verbose_name='Admin destinataire'),
        ),
        migrations.AlterField(
            model_name='notificationadmin',
            name='lu_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_lues', to=settings.AUTH_USER_MODEL, verbose_name='Lu par'),
        ),
    ]
