# Generated by Django 4.2.7 on 2026-04-23 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gestion', '0004_notificationadmin_utilisateur_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationadmin',
            name='lu_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
