# Generated by Django 4.2.7 on 2026-07-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_alter_notificationadmin_lu_par'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fichier', models.CharField(max_length=255)),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('donnees', models.JSONField(default=list)),
                ('dates_disponibles', models.JSONField(default=list)),
                ('nombre_lignes', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Planning Excel',
                'verbose_name_plural': 'Plannings Excel',
                'ordering': ['-date_upload'],
            },
        ),
    ]
