# Generated by Django 4.2.7 on 2026-07-03 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_planningexcel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planningexcel',
            name='dates_disponibles',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='planningexcel',
            name='donnees',
            field=models.TextField(default='[]'),
        ),
    ]
