from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('tableau-de-bord/', views.tableau_de_bord, name='tableau_de_bord'),
    path('upload/', views.upload_files, name='upload'),
    path('transports/', views.liste_transports, name='liste_transports'),
    path('transports/pdf/', views.generer_pdf, name='generer_pdf'),
    path('chauffeurs/', views.gestion_chauffeurs, name='chauffeurs'),
    path('chauffeurs/ajouter/', views.ajouter_chauffeur, name='ajouter_chauffeur'),
    path('chauffeurs/supprimer/<int:id>/', views.supprimer_affectation, name='supprimer_affectation'),
    path('chauffeurs/supprimer-course/<int:id>/', views.supprimer_course, name='supprimer_course'),
    path('chauffeurs/api/agents_non_affectes/', views.get_agents_non_affectes, name='get_agents_non_affectes'),
    path('chauffeurs/api/heures_par_type/', views.get_heures_par_type, name='get_heures_par_type'),
    path('paie/', views.rapport_paie, name='paie'),
    path('paie/societe/<str:societe_nom>/', views.detail_societe_paie, name='detail_societe_paie'),
    path('agents/', views.gestion_agents, name='agents'),
    path('agents/modifier/<int:id>/', views.modifier_agent, name='modifier_agent'),
    path('agents/supprimer/<int:id>/', views.supprimer_agent, name='supprimer_agent'),
    path('agents/detail/<int:id>/', views.detail_agent, name='detail_agent'),
    path('agents/importer/', views.importer_agents, name='importer_agents'),
    path('societes/', views.gestion_societes, name='societes'),
    path('societes/modifier/<int:id>/', views.modifier_societe, name='modifier_societe'),
    path('societes/supprimer/<int:id>/', views.supprimer_societe, name='supprimer_societe'),
    path('societes/detail/<int:id>/', views.detail_societe, name='detail_societe'),
    path('chauffeurs/api/agents_du_planning/', views.get_agents_du_planning, name='get_agents_du_planning'),
    path('societes/api/liste/', views.api_liste_societes, name='api_liste_societes'),
    path('agents/api/modifier/', views.api_modifier_agent, name='api_modifier_agent'),
    path('agents/supprimer_multiple/', views.supprimer_agents_multiple, name='supprimer_agents_multiple'),
    path('chauffeurs/api/carte_course/<int:course_id>/', views.api_carte_course, name='api_carte_course'),
    path('validation/valider-course/<int:course_id>/', views.valider_course_admin, name='valider_course_admin'),
    path('validation/refuser-course/<int:course_id>/', views.refuser_course_admin, name='refuser_course_admin'),
    path('validation/courses-attente/', views.courses_en_attente_validation, name='courses_en_attente_validation'),
    path('logs/hors-planning/', views.voir_logs_hors_planning, name='logs_hors_planning'),
]
