# Generated by Django 4.2.7 on 2026-03-12 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('reservation', 'Nouvelle réservation'), ('annulation', 'Annulation de réservation'), ('info', 'Information'), ('alerte', 'Alerte'), ('super_reservation', 'Réservation par Super Chauffeur'), ('super_annulation', 'Annulation par Super Chauffeur'), ('agent_selection', 'Agent à transporter'), ('transport_confirmation', 'Confirmation transport')], max_length=25)),
                ('message', models.TextField()),
                ('vue', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('date_transport', models.DateField(blank=True, null=True)),
                ('type_transport', models.CharField(blank=True, choices=[('ramassage', 'Ramassage'), ('depart', 'Départ'), ('', 'Non spécifié')], default='', max_length=20)),
                ('groupe_notification', models.CharField(blank=True, help_text='Clé pour grouper les notifications par heure', max_length=100)),
                ('chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_mobile', to='gestion.chauffeur')),
                ('heure_transport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='gestion.heuretransport')),
            ],
            options={
                'verbose_name': 'Notification mobile',
                'verbose_name_plural': 'Notifications mobiles',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['groupe_notification', '-created_at'], name='chauffeurs__groupe__4f3e85_idx'), models.Index(fields=['chauffeur', 'vue', 'created_at'], name='chauffeurs__chauffe_d177e7_idx')],
            },
        ),
        migrations.CreateModel(
            name='MobileCourseStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut_mobile', models.CharField(choices=[('a_faire', 'À faire'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('validee', 'Validée'), ('probleme', 'Problème')], default='a_faire', max_length=20)),
                ('heure_reelle', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.chauffeur')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion.course')),
            ],
            options={
                'verbose_name': 'Statut mobile',
                'verbose_name_plural': 'Statuts mobiles',
                'unique_together': {('course', 'chauffeur')},
            },
        ),
    ]
