# Generated by Django 4.2.7 on 2026-07-03 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chauffeurs_mobile', '0002_planningexcel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PlanningExcel',
        ),
    ]
